/**
 * Platform packaging helpers (metadata for Electron/Tauri/itch builds).
 * Does not ship a full desktop shell — provides manifests games can consume.
 */

export interface GamePackageManifest {
  id: string;
  title: string;
  version: string;
  description?: string;
  /** Relative path to built web dist */
  webDist: string;
  window: {
    width: number;
    height: number;
    fullscreen?: boolean;
  };
  itch?: {
    channel: string;
  };
  steam?: {
    appId?: string;
  };
}

export function createPackageManifest(
  partial: Partial<GamePackageManifest> &
    Pick<GamePackageManifest, "id" | "title">,
): GamePackageManifest {
  return {
    id: partial.id,
    title: partial.title,
    version: partial.version ?? "0.1.0",
    description: partial.description,
    webDist: partial.webDist ?? "dist-web",
    window: {
      width: partial.window?.width ?? 1280,
      height: partial.window?.height ?? 720,
      fullscreen: partial.window?.fullscreen ?? false,
    },
    itch: partial.itch,
    steam: partial.steam,
  };
}

/** Minimal Electron main-process template as a string (write to disk in tools). */
export function electronMainTemplate(manifest: GamePackageManifest): string {
  return `// Generated by @anvil/core platform helper — Electron main
const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindow() {
  const win = new BrowserWindow({
    width: ${manifest.window.width},
    height: ${manifest.window.height},
    fullscreen: ${manifest.window.fullscreen ? "true" : "false"},
    webPreferences: { nodeIntegration: false, contextIsolation: true },
    title: ${JSON.stringify(manifest.title)},
  });
  win.loadFile(path.join(__dirname, ${JSON.stringify(manifest.webDist)}, 'index.html'));
}

app.whenReady().then(createWindow);
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
`;
}
